#
# This source file is part of the SpeziStudyServer open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

generate:
  - types
  - server
namingStrategy: idiomatic
additionalImports:
  - SpeziLocalization
  - SpeziHealthKit
typeOverrides:
  schemas:
    InformationalContent: SpeziStudyServer.InformationalContent
    InformationalComponentData: SpeziLocalization.LocalizationsDictionary<SpeziStudyServer.InformationalContent>
    QuestionnaireContent: SpeziStudyServer.QuestionnaireContent
    QuestionnaireComponentData: SpeziLocalization.LocalizationsDictionary<SpeziStudyServer.QuestionnaireContent>
    LocalizedString: "SpeziLocalization.LocalizationsDictionary<Swift.String>"
    StudyDetailContent: SpeziStudyServer.StudyDetailContent
    StudyDetailData: "SpeziLocalization.LocalizationsDictionary<SpeziStudyServer.StudyDetailContent>"
    SampleTypesCollection: "[SpeziHealthKit.SampleTypeProxy]"
