#
# This source file is part of the SpeziStudyServer open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

generate:
  - types
  - server
namingStrategy: idiomatic
additionalImports:
  - SpeziLocalization
typeOverrides:
  schemas:
    InformationalContent: SpeziStudyServer.InformationalContent
    InformationalComponentData: SpeziLocalization.LocalizedDictionary<SpeziStudyServer.InformationalContent>
    QuestionnaireContent: SpeziStudyServer.QuestionnaireContent
    QuestionnaireComponentData: SpeziLocalization.LocalizedDictionary<SpeziStudyServer.QuestionnaireContent>
    HealthDataComponentData: SpeziStudyServer.HealthDataContent
